services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: capstone-app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8000:80"
    environment:
      APP_ENV: local
      APP_DEBUG: true
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/var/www/html

  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reverb
    working_dir: /var/www/html
    command: >
      sh -c "sleep 10 &&
             php artisan reverb:start --host=0.0.0.0 --port=6001"
    ports:
      - "6001:6001"
    environment:
      REVERB_SERVER_HOST: 0.0.0.0
      REVERB_SERVER_PORT: 6001
      REVERB_SCHEME: http
    depends_on:
      - app
      - mysql
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
